name: Continuous build
on:
  push:
    branches:
      - '**'
jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name:
        uses: actions/download-artifact@v4
        with:
          name: Launcher

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest build
          files: |
            Launcher.exe
